### PR TITLE
adding WANPPPConnection ServiceType

### PR DESCRIPTION
**Pull request by cyberb**
According to: https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/igd_desc_parse.c#L50
That fixed my BT Home Router.

### CODE REVIEW

**Comment by cyberb** [comment]
Sorry, made a mistake in commit message: WANIPConnection -> WANPPPConnection

**Comment by cyberb** [comment]
Sorry, made a mistake in the commit message: WANIPConnection -> WANPPPConnection

**Comment by abahgat** [comment]
Thanks!

**Comment by cyberb** [comment]
Do you plan to publish new version to maven some time soon?

**Comment by abahgat** [comment]
Hey Boris, 0.1.3 is available on Maven.
Apologies for the delay

**Pull request merged**
